---
exclude: ['README.markdown']
permalink: ':title'
highlighter: pygments
safe: false
title: 'Carte'
markdown: redcarpet
redcarpet:
  extensions: 
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - with_toc_data
    - tables
    - strikethrough